const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

const setupBat = [
  '@echo off',
  'chcp 65001 >nul',
  'title Parallax Studio - Cai dat thu vien',
  'cd /d "%~dp0"',
  '',
  'echo ============================================================',
  'echo      Parallax Studio - Cai dat moi truong va thu vien',
  'echo ============================================================',
  'echo.',
  '',
  'REM 1. Kiem tra Node.js',
  'where node >nul 2>nul',
  'if %errorlevel% neq 0 (',
  '    echo [LOI] Khong tim thay Node.js tren may tinh!',
  '    echo.',
  '    echo Vui long tai va cai dat Node.js LTS - phien ban 20 tro len tai:',
  '    echo https://nodejs.org/',
  '    echo.',
  '    echo Sau khi cai xong, hay khoi dong lai Command Prompt hoac may tinh.',
  '    echo.',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'echo [OK] Da tim thay Node.js:',
  'node -v',
  'echo.',
  '',
  'REM 2. Cai dat thu vien ung dung goc',
  'echo [1/2] Dang cai dat thu vien ung dung chinh [npm install]...',
  'call npm install',
  'if %errorlevel% neq 0 (',
  '    echo.',
  '    echo [LOI] Cai dat thu vien ung dung chinh that bai!',
  '    echo Vui long kiem tra ket noi mang va thu lai.',
  '    echo.',
  '    pause',
  '    exit /b %errorlevel%',
  ')',
  'echo [OK] Da cai dat xong thu vien chinh.',
  'echo.',
  '',
  'REM 3. Cai dat thu vien MCP Server',
  'echo [2/2] Dang cai dat thu vien cho MCP Server [mcp-server]...',
  'call npm run mcp:install',
  'if %errorlevel% neq 0 (',
  '    echo.',
  '    echo [LOI] Cai dat thu vien MCP Server that bai!',
  '    echo.',
  '    pause',
  '    exit /b %errorlevel%',
  ')',
  'echo [OK] Da cai dat xong thu vien MCP Server.',
  'echo.',
  '',
  'echo ============================================================',
  'echo   CAI DAT HOAN TAT THANH CONG!',
  'echo   Bay gio ban co the chay "start.bat" de mo ung dung.',
  'echo ============================================================',
  'echo.',
  '',
  'if "%~1"=="--no-pause" goto :done',
  'pause',
  ':done',
  ''
].join('\r\n');

const startBat = [
  '@echo off',
  'chcp 65001 >nul',
  'title Parallax Studio',
  'cd /d "%~dp0"',
  '',
  'echo ============================================================',
  'echo      Parallax Studio - Khoi dong ung dung',
  'echo ============================================================',
  'echo.',
  '',
  'REM 1. Kiem tra Node.js',
  'where node >nul 2>nul',
  'if %errorlevel% neq 0 (',
  '    echo [LOI] Khong tim thay Node.js tren may tinh!',
  '    echo Vui long tai va cai dat Node.js LTS tai: https://nodejs.org/',
  '    echo.',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'REM 2. Tu dong kiem tra va cai dat neu chua co node_modules',
  'if not exist "%~dp0node_modules\\" (',
  '    echo [THONG BAO] Phat hien chua cai dat thu vien ung dung.',
  '    echo Dang tu dong tien hanh cai dat lan dau...',
  '    echo.',
  '    call "%~dp0setup.bat" --no-pause',
  '    if %errorlevel% neq 0 (',
  '        echo [LOI] Cai dat tu dong that bai!',
  '        pause',
  '        exit /b 1',
  '    )',
  '    echo.',
  ')',
  '',
  'if not exist "%~dp0mcp-server\\node_modules\\" (',
  '    echo [THONG BAO] Dang cai dat bo sung thu vien MCP Server...',
  '    call npm run mcp:install',
  '    echo.',
  ')',
  '',
  'REM 3. Khoi chay ung dung',
  'echo Dang khoi dong Parallax Studio...',
  'echo [Nhan Ctrl+C trong cua so nay neu muon dung ung dung]',
  'echo.',
  '',
  'call npm run dev',
  'if %errorlevel% neq 0 (',
  '    echo.',
  '    echo [LOI] Ung dung da dung voi ma loi %errorlevel%.',
  '    pause',
  ')',
  ''
].join('\r\n');

const buildBat = [
  '@echo off',
  'chcp 65001 >nul',
  'title Parallax Studio - Build Production',
  'cd /d "%~dp0"',
  '',
  'echo ============================================================',
  'echo      Parallax Studio - Build Production Bundle',
  'echo ============================================================',
  'echo.',
  '',
  'where node >nul 2>nul',
  'if %errorlevel% neq 0 (',
  '    echo [LOI] Khong tim thay Node.js!',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'if not exist "%~dp0node_modules\\" (',
  '    echo [THONG BAO] Dang cai dat thu vien truoc khi build...',
  '    call "%~dp0setup.bat" --no-pause',
  ')',
  '',
  'echo Dang build ung dung [npm run build]...',
  'call npm run build',
  'if %errorlevel% neq 0 (',
  '    echo.',
  '    echo [LOI] Qua trinh build that bai!',
  '    pause',
  '    exit /b %errorlevel%',
  ')',
  '',
  'echo.',
  'echo ============================================================',
  'echo   BUILD THANH CONG! File dau ra nam trong thu muc: out/',
  'echo ============================================================',
  'echo.',
  'pause',
  ''
].join('\r\n');

fs.writeFileSync(path.join(rootDir, 'setup.bat'), setupBat, 'utf8');
fs.writeFileSync(path.join(rootDir, 'start.bat'), startBat, 'utf8');
fs.writeFileSync(path.join(rootDir, 'build.bat'), buildBat, 'utf8');
console.log('Regenerated setup.bat, start.bat, build.bat with CRLF and safe syntax');
